# If problem "ethereum not found" => Replace the RUN by multiple RUN (one by line)

FROM ubuntu:latest

COPY genesis.json /tmp

RUN apt-get update && apt-get install -y software-properties-common  \
    && add-apt-repository -y ppa:ethereum/ethereum  \
    && apt-get update  \
    && apt-get install -y ethereum  \
    && apt-get install -y solc  \
    && apt-get install -y nano
